JOBS_SEARCH_KEYWORDS = {
    "Android": ["Android", "", ""],
    "Angular": ["Angular", "", ""],
    "AWS": ["AWS", "", ""],
    "Azure": ["Azure", "", ""],
    "Big Data": ["Big Data", "", ""],
    "CSharp": ["CSharp", "", ""],
    "Cplusplus": ["Cplusplus", "", ""],
    "Cloud": ["Cloud", "", ""],
    "DevOps": ["DevOps", "", ""],
    "Flutter": ["Flutter", "", ""],
    "Front End": ["Front End", "", ""],
    "Go": ["Go", "", ""],
    "JAVA": ["JAVA", "", ""],
    "JavaScript": ["JavaScript", "", ""],
    ".NET": [".NET", "", ""],
    ".NET Core": [".NET Core", "", ""],
    "NoSQL": ["NoSQL", "", ""],
    "Node.JS": ["Node.JS", "", ""],
    "Oracle": ["Oracle", "", ""],
    "PHP": ["PHP", "", ""],
    "Python": ["Python", "", ""],
    "SQL": ["SQL", "", ""],
    "QA": ["QA", "", ""],
    "ReactJs": ["ReactJs", "", ""],
    "React Native": ["React Native", "", ""],
    "Ruby": ["Ruby", "", ""],
    "Swift": ["Swift", "", ""],
    "Vue": ["Vue", "", ""],
    "BlockChain": ["BlockChain", "", ""],
    "Golang": ["Golang", "", ""],
    "IOS": ["IOS", "", ""],
    "Data Science": ["Data Science", "", ""],
    "UI/UX": ["UI/UX", "", ""],
    "Designer": ["Designer", "", ""],
    "Tech Lead": ["Tech Lead", "", ""],
    "security": ["security", "", ""],
    "Back-end": ["Back-end", "", ""],
    "Full Stack": ["Full Stack", "", ""],
    "DBA": ["DBA", "", ""],
}
